### ISSUE TITLE
Incompatible with the lates MAUI SDK

### ISSUE THREAD

**Issue by CyborTronik** [marcojak/MauiMTAdmob#92]
Unable to install the package for MAUI SDK 8.0.80
getting the following error:
```
Package restore failed. Rolling back package changes for '<app name>'.
Version conflict detected for Xamarin.AndroidX.Lifecycle.LiveData.Core. Install/reference Xamarin.AndroidX.Lifecycle.LiveData.Core 2.8.4 directly to project Anti-Food to resolve this issue. 
 Anti-Food -> Xamarin.AndroidX.Fragm ... droidX.Lifecycle.LiveData.Core (>= 2.8.4 && < 2.8.5) 
 Anti-Food -> Plugin.MauiMTAdmob 1.5.1 -> Xamarin.GooglePlayServices.Ads.Lite 122.3.0.3 -> Xamarin.AndroidX.Work.Runtime 2.9.0 -> Xamarin.AndroidX.Lifecycle.LiveData 2.6.2.3 -> Xamarin.AndroidX.Lifecycle.LiveData.Core (>= 2.6.2.3 && < 2.6.3).
```

A downgrade of `Xamarin.AndroidX.Lifecycle.LiveData.Core` is not possible due to other deps.

**Comment by marcojak** [comment]
If you manually install Xamarin.AndroidX.Lifecycle.LiveData.Core 2.8.4 it will work.

However I'm going to release a new version of the plugin in a bit, so it shouldn't be necessary

**Comment by marcojak** [comment]
Version 1.6.0 should be online in the next couple of minutes.
Closing for now.
If there are issues, please open a new issue

**Comment by CyborTronik** [comment]
@marcojak please check the last line from the message. It says that I cannot use downgraded version. It simply won't work with MAUI 8.0.80, may work with older versions.
Please reconsider this, and reopen the issue. Overall is not ok to downgrade SDK for relative basic thing.

**Comment by marcojak** [comment]
@CyborTronik  I don't understand.
The new version of the plugin uses Xamarin.GooglePlayServices.Ads.Lite 123.0.0 that uses Xamarin.AndroidX.Work.Runtime 2.9.0.5 that uses Xamarin.AndroidX.Lifecycle.LiveData >= 2.8.3.1 that uses Xamarin.AndroidX.Lifecycle.LiveData.Core (>= 2.8.4 && < 2.8.5)

So it's perfectly in line with your requirements.

If this is not enough, could you please explain what you need?

**Comment by CostasAthan** [comment]
In my case in order to update `MauiMTAdmob` to version 1.6.0, along with `Xamarin.Google.UserMessagingPlatform` to version 3.0.0 and `Xamarin.GooglePlayServices.Ads.Lite` to version 123.1.0 (the same is also true for version 123.0.0), I had to install the following packages otherwise I was getting an error during deployment:

1. `Xamarin.GooglePlayServices.Measurement`
2. `Xamarin.GooglePlayServices.Measurement.Api`
3. `Xamarin.GooglePlayServices.Measurement.Sdk`

all 3 in version 122.0.2.

The error I was getting was the following:

> 1>MSBUILD : java.exe error JAVA0000: Error in obj\Debug\net8.0-android34.0\lp\243\jl\classes.jar:com/google/android/gms/measurement/internal/zzip.class:
> 1>MSBUILD : java.exe error JAVA0000: Type com.google.android.gms.measurement.internal.zzip is defined multiple times: obj\Debug\net8.0-android34.0\lp\243\jl\classes.jar:com/google/android/gms/measurement/internal/zzip.class, obj\Debug\net8.0-android34.0\lp\244\jl\classes.jar:com/google/android/gms/measurement/internal/zzip.class
> 1>MSBUILD : java.exe error JAVA0000: Compilation failed

**Comment by CyborTronik** [comment]
It requires some dependencies to be updated yet, all of the following deps need to be to 2.8.4,  it fails when downgrading to 2.8.3.1
```
Xamarin.AndroidX.Lifecycle.Common
Xamarin.AndroidX.Lifecycle.LiveData.Core
Xamarin.AndroidX.Lifecycle.LiveData.Core.Ktx
Xamarin.AndroidX.Lifecycle.LiveData
Xamarin.AndroidX.Lifecycle.Runtime
Xamarin.AndroidX.Lifecycle.Service
```

**Comment by CyborTronik** [comment]
@marcojak works with version 1.6.1.
Thank you for your quick fix
